name: Penny Scan to Discord

on:
  schedule:
    # 14:35 UTC Mon–Fri ≈ 9:35am ET during DST
    - cron: "35 14 * * 1-5"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # --- Tighter filters so runs finish quickly & reliably ---
          TOP_N: "8"                 # fewer final picks
          MIN_PRICE: "0.50"          # skip sub-50c names
          MAX_PRICE: "3.0"           # tighter price band (raise later if you want)
          MIN_AVG_VOL: "500000"      # require higher average volume
          VOL_RATIO_THRESHOLD: "4.0" # bigger volume surge
          PCT_CHANGE_MIN: "8.0"      # stronger move required
          NEWS_LOOKBACK_DAYS: "0"    # disable news for now (avoids yfinance flakiness)
        run: |
          python scanner.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: penny-scan-${{ github.run_id }}
          path: |
            *.csv