name: Penny Scan to Discord
      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TOP_N: "8"                # fewer final picks
          MIN_PRICE: "0.50"         # skip the very illiquid sub-50c names
          MAX_PRICE: "3.0"          # tighter price band
          MIN_AVG_VOL: "500000"     # require higher average volume
          VOL_RATIO_THRESHOLD: "4.0"# need bigger volume surge
          PCT_CHANGE_MIN: "8.0"     # stronger move required
          NEWS_LOOKBACK_DAYS: "0"   # keep news disabled for now