name: Penny Scan to Discord

on:
  schedule:
    - cron: "35 14 * * 1-5"   # 14:35 UTC Mon–Fri (~9:35am ET DST)
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scanner
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TOP_N: "12"
          MIN_PRICE: "0.25"
          MAX_PRICE: "5.0"
          MIN_AVG_VOL: "200000"
          VOL_RATIO_THRESHOLD: "3.0"
          PCT_CHANGE_MIN: "5.0"
          NEWS_LOOKBACK_DAYS: "2"
        run: |
          python scanner.py
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: penny-scan-${{ github.run_id }}
          path: |
            *.csv
